name: Test python build on linux
on: [workflow_dispatch]

jobs:
  build-manylinux2014-x86_64-wheels:
    name: "Build Manylinux 2014 aarch64 wheel"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: lightspark-crypto-python
    container:
      image: quay.io/pypa/manylinux2014_aarch64
      env:
        PLAT: manylinux2014_aarch64
        PYBIN: "/opt/python/${{ matrix.python }}/bin"
    strategy:
      matrix:
        python: # Update this list whenever the docker image is updated (check /opt/python/)
          - cp310-cp310
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo tree
        run: cargo tree

      - name: "Generate py source and binaries"
        run: bash ./scripts/generate-linux.sh

      - name: "Build wheel"
        run: ${PYBIN}/python setup.py bdist_wheel --plat-name manylinux_2_17_aarch64 --verbose

      - run: pwd
      - run: ls dist

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: lightspark_crypto_python-manylinux2014-aarch64-${{ matrix.python }}
          path: /home/runner/work/lightspark-crypto-uniffi/lightspark-crypto-python/dist/*.whl
